### PR TITLE
Enable CORS when Origin header is present

### PR DESCRIPTION
**Pull request by zBNF**
Should resolve https://github.com/CryptoBlades/cryptoblades/issues/487

---

Wasn't able to test this but it should be sufficient for now. It assumes we only want to let browsers make requests to the API from `https://app.cryptoblades.io` and if the Origin header is not set, we disable CORS entirely.

### CODE REVIEW

**Comment by zBNF** [comment]
Just realized we'll need to add a way to disable CORS in dev mode. Is `NODE_ENV=production` or similar used in prod?

**Comment by seiyria** [comment]
Can you fix these merge errors? And also, I would like it to run on *.cryptoblades if you can make that change. The main site will need to hit the api periodically for stats.

**Comment by zBNF** [comment]
It's not a great idea to use regular expressions here IMO unless absolutely necessary (unknown number of TLDs). Something simple like `includes('cryptoblades.io')` can be bypassed by subdomains (e.g. https://cryptoblades.io.example.com). IMO it's better to have an explicit list and simply reflect if the supplied Origin is in the list. Thoughts?

**Comment by seiyria** [comment]
fine with me.

**Pull request merged**
