### PR TITLE
Import all market entries

### PR DESCRIPTION
**Pull request by OPPandaDeFi**

### CODE REVIEW

**Comment by seiyria** [comment]
@OPPandaDeFi no worries, you can still collect a bounty for it. I need this sort of thing anyway so I'll see if I can merge the two solutions.

**Comment by seiyria** [comment]
@OPPandaDeFi my only question here is where this multicall ABI came from. I don't see it in our repo. Is there a better way to get a hold of it besides adding it to the repo (ie, including it as part of the build for the frontend)?

**Review by seiyria — APPROVED** [review]

**Comment by OPPandaDeFi** [comment]
The multicall ABI, I just pulled this from PancakeSwap. 

You could release your own version of the contract. You could also include it in the frontend and pull like you already do.

**Comment by seiyria** [comment]
Thanks. Good to know, but unimportant to me if it's not something we already have.

**Pull request merged**
