### PR TITLE
730-market-filters-broken-api

### PR DESCRIPTION
**Pull request by bilbolPrime**
Modify the way stars filter is handled to properly handle Any.
1 star weapons will send 0 to API which would conflict with all

Needed with https://github.com/CryptoBlades/cryptoblades/pull/731/files to fix https://github.com/CryptoBlades/cryptoblades/issues/730

### CODE REVIEW

**Comment by bilbolPrime** [comment]
@seiyria just in case you missed this request as you have already merged the frontend one. This is needed otherwise filtering for 1 star items would conflict with any star items.
It's not critical as I doubt anyone would filter for 1 star but it is a needed fix.

**Comment by bilbolPrime** [comment]
> 
> 
> This isn't quite the right fix for this. It should be using `??` instead of `||`

Used ?? as requested however I think the === 0 check on max star is still needed; If(maxStar) is giving false when it's a 0 number so it's falling back to any star when filtering on 1 star.

**Comment by seiyria** [comment]
In that case, they should be >= 0, instead of a separate check for === 0.

**Comment by bilbolPrime** [comment]
Thinking about this again, if(maxStars || maxStars === 0) or if(maxStars >= 0) will always be true.
I pushed maxStars !== maxStarValue where maxStarValue is a 4 constant

**Comment by seiyria** [comment]
That would mean we can't search for the max value. Did you try that out? It doesn't look at a glance like it would work.

**Comment by bilbolPrime** [comment]
Yup I tested it. If maxStar = 4 then we just don't add the less than or equal condition => all is returned

**Pull request merged**
