### PR TITLE
Marketplace Realtime Updates, Fixing Sold Item Pages

### PR DESCRIPTION
**Pull request by mentalrob**
Hey guys, I created this PR due to market issues

**Issues**

- [x] Every page is full of sold weapons or characters
- [x] Sometimes search cannot finds the listed items with id

I just created this PR with some basic structural code. But I don't know if this repo is open to contrubitions, so let me know if it's okay to do this so that i can move on

Thanks

### CODE REVIEW

**Comment by mentalrob** [comment]
@seiyria

**Comment by seiyria** [comment]
Thanks for the contribution. I'll take a look at this, as this is in line with what we want to do anyway.

**Comment by mentalrob** [comment]
Okay i will make furthure development for this PR then, when you check it let me know

**Comment by mentalrob** [comment]
I made some updates @seiyria can you check please ?

**Comment by seiyria** [comment]
Thanks for the changes. I'm doing a lot of manual work to merge this and make it fit our style a bit more. I put the ABIs up on the frontend and those will now be downloaded when the app starts, etc. Just a lot of work and I hope to finish it today!

**Comment by seiyria** [comment]
@mentalrob thanks for this, it helped a lot. Are you able to help in making a recurring task to clean up sold items as well? I scaffolded the task but I'm admittedly not sure how to query the prices on the blockchain.

**Pull request merged**
